-- Pharmacy Batch & Expiry Management System
-- Normalized Oracle 23ai schema with integrity constraints.

CREATE TABLE category (
  category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR2(100) NOT NULL UNIQUE,
  description VARCHAR2(250)
);

CREATE TABLE medicine (
  medicine_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medicine_name VARCHAR2(150) NOT NULL,
  generic_name VARCHAR2(150),
  dosage_form VARCHAR2(50),
  strength VARCHAR2(50),
  category_id NUMBER NOT NULL,
  manufacturer VARCHAR2(150),
  reorder_level NUMBER DEFAULT 10 NOT NULL,
  CONSTRAINT fk_medicine_category FOREIGN KEY (category_id) REFERENCES category(category_id),
  CONSTRAINT chk_reorder_level CHECK (reorder_level >= 0)
);

CREATE TABLE supplier (
  supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_name VARCHAR2(150) NOT NULL UNIQUE,
  contact_person VARCHAR2(100),
  phone VARCHAR2(20),
  email VARCHAR2(150) UNIQUE,
  address VARCHAR2(300)
);

CREATE TABLE medicine_batch (
  batch_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medicine_id NUMBER NOT NULL,
  batch_number VARCHAR2(50) NOT NULL,
  manufacture_date DATE,
  expiry_date DATE NOT NULL,
  selling_price NUMBER(10,2) NOT NULL,
  quantity_available NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT fk_batch_medicine FOREIGN KEY (medicine_id) REFERENCES medicine(medicine_id),
  CONSTRAINT uq_medicine_batch UNIQUE (medicine_id, batch_number),
  CONSTRAINT chk_batch_dates CHECK (manufacture_date IS NULL OR expiry_date > manufacture_date),
  CONSTRAINT chk_selling_price CHECK (selling_price >= 0),
  CONSTRAINT chk_batch_quantity CHECK (quantity_available >= 0)
);

CREATE TABLE purchase (
  purchase_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id NUMBER NOT NULL,
  purchase_date DATE DEFAULT SYSDATE NOT NULL,
  invoice_number VARCHAR2(50) NOT NULL UNIQUE,
  total_amount NUMBER(12,2) DEFAULT 0 NOT NULL,
  CONSTRAINT fk_purchase_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id),
  CONSTRAINT chk_purchase_total CHECK (total_amount >= 0)
);

CREATE TABLE purchase_item (
  purchase_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id NUMBER NOT NULL,
  batch_id NUMBER NOT NULL,
  quantity NUMBER NOT NULL,
  unit_price NUMBER(10,2) NOT NULL,
  subtotal NUMBER(12,2) NOT NULL,
  CONSTRAINT fk_pi_purchase FOREIGN KEY (purchase_id) REFERENCES purchase(purchase_id),
  CONSTRAINT fk_pi_batch FOREIGN KEY (batch_id) REFERENCES medicine_batch(batch_id),
  CONSTRAINT uq_purchase_batch UNIQUE (purchase_id, batch_id),
  CONSTRAINT chk_pi_quantity CHECK (quantity > 0),
  CONSTRAINT chk_pi_price CHECK (unit_price >= 0),
  CONSTRAINT chk_pi_subtotal CHECK (subtotal = ROUND(quantity * unit_price, 2))
);

CREATE TABLE customer (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR2(150) NOT NULL,
  phone VARCHAR2(20) UNIQUE,
  email VARCHAR2(150) UNIQUE
);

CREATE TABLE sale (
  sale_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER,
  sale_date DATE DEFAULT SYSDATE NOT NULL,
  payment_method VARCHAR2(20) DEFAULT 'CASH' NOT NULL,
  total_amount NUMBER(12,2) DEFAULT 0 NOT NULL,
  CONSTRAINT fk_sale_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
  CONSTRAINT chk_payment_method CHECK (payment_method IN ('CASH','CARD','UPI','OTHER')),
  CONSTRAINT chk_sale_total CHECK (total_amount >= 0)
);

CREATE TABLE sale_item (
  sale_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id NUMBER NOT NULL,
  batch_id NUMBER NOT NULL,
  quantity NUMBER NOT NULL,
  unit_price NUMBER(10,2) NOT NULL,
  subtotal NUMBER(12,2) NOT NULL,
  CONSTRAINT fk_si_sale FOREIGN KEY (sale_id) REFERENCES sale(sale_id),
  CONSTRAINT fk_si_batch FOREIGN KEY (batch_id) REFERENCES medicine_batch(batch_id),
  CONSTRAINT uq_sale_batch UNIQUE (sale_id, batch_id),
  CONSTRAINT chk_si_quantity CHECK (quantity > 0),
  CONSTRAINT chk_si_price CHECK (unit_price >= 0),
  CONSTRAINT chk_si_subtotal CHECK (subtotal = ROUND(quantity * unit_price, 2))
);

CREATE TABLE alert (
  alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id NUMBER NOT NULL,
  alert_type VARCHAR2(30) NOT NULL,
  alert_date DATE DEFAULT SYSDATE NOT NULL,
  message VARCHAR2(300),
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT fk_alert_batch FOREIGN KEY (batch_id) REFERENCES medicine_batch(batch_id),
  CONSTRAINT chk_alert_type CHECK (alert_type IN ('EXPIRING_SOON','EXPIRED')),
  CONSTRAINT chk_alert_status CHECK (status IN ('ACTIVE','RESOLVED'))
);

CREATE INDEX idx_batch_expiry ON medicine_batch(expiry_date);
CREATE INDEX idx_batch_medicine ON medicine_batch(medicine_id);
CREATE INDEX idx_purchase_supplier ON purchase(supplier_id);
CREATE INDEX idx_sale_customer ON sale(customer_id);
